import type { Locale } from "./site-context";

export type PageKey =
  | "features"
  | "workflow"
  | "pricing"
  | "download"
  | "mobile"
  | "watch"
  | "desktop"
  | "integrations"
  | "help"
  | "about"
  | "contact"
  | "privacy"
  | "terms";

export type Action = {
  label: string;
  href: string;
  external?: boolean;
};

export type DetailSection = {
  id: string;
  eyebrow?: string;
  title: string;
  body: string;
  bullets?: string[];
  image?: string;
  imageAlt?: string;
  actions?: Action[];
};

export type DetailCopy = {
  group: string;
  title: string;
  lead: string;
  heroImage: string;
  heroAlt: string;
  primary: Action;
  secondary?: Action;
  highlights: Array<{ value: string; label: string }>;
  sections: DetailSection[];
  related: PageKey[];
};

export const externalLinks = {
  account: "https://ideasnap.xyz/",
  appStore:
    "https://apps.apple.com/cn/app/%E9%97%AA%E5%BF%B5-ai%E8%AF%AD%E9%9F%B3%E7%AC%94%E8%AE%B0/id1397149726",
  android:
    "https://dl.northcity.top/1.0.18/%E9%97%AA%E5%BF%B5%E7%AC%94%E8%AE%B0_v1.0.18_release.apk",
  windowsSetup:
    "https://dl.northcity.top/1.0.18/%E9%97%AA%E5%BF%B5%20Setup%201.0.18.exe",
  windowsPortable:
    "https://dl.northcity.top/1.0.18/%E9%97%AA%E5%BF%B5%201.0.18.exe",
  macos:
    "https://dl.northcity.top/1.0.18/%E9%97%AA%E5%BF%B5-1.0.18-stapled.dmg",
  linuxDeb:
    "https://dl.northcity.top/1.0.18/shannian-desktop_1.0.18_amd64.deb",
  linuxAppImage:
    "https://dl.northcity.top/1.0.18/%E9%97%AA%E5%BF%B5-1.0.18.AppImage",
  checkout: "/pricing#pricing-plans",
  privacy: "https://www.northcity.top/ideasnap-privacy-policy/",
  terms: "https://www.northcity.top/ideasnap-subscription-agreement/",
  updates: "https://www.northcity.top/logs/2025-11-15-shannian-featured/",
  developer: "https://www.northcity.top/about/",
};

export const commonCopy = {
  zh: {
    brand: "闪念",
    tagline: "AI 语音笔记",
    nav: [
      ["功能", "/features"],
      ["使用方法", "/workflow"],
      ["定价", "/pricing"],
      ["下载", "/download"],
    ],
    download: "免费下载",
    account: "登录 / 注册",
    accountTitle: "前往闪念官网登录或注册",
    themeLight: "切换到浅色模式",
    themeDark: "切换到深色模式",
    language: "切换到英文",
    footerNote: "开口记录，AI 自动整理。由独立开发者北城长期维护。",
    groups: [
      {
        title: "产品",
        links: [
          ["桌面端", "/desktop"],
          ["手机端", "/mobile"],
          ["手表端", "/watch"],
          ["联动与 AI", "/integrations"],
        ],
      },
      {
        title: "资源",
        links: [
          ["功能总览", "/features"],
          ["使用方法", "/workflow"],
          ["下载与安装", "/download"],
          ["帮助与常见问题", "/help"],
          ["会员定价", "/pricing"],
        ],
      },
      {
        title: "关于",
        links: [
          ["关于闪念", "/about"],
          ["联系我们", "/contact"],
          ["关于北城", externalLinks.developer],
          ["更新动态", externalLinks.updates],
        ],
      },
      {
        title: "法律",
        links: [
          ["隐私说明", "/privacy"],
          ["服务条款", "/terms"],
        ],
      },
    ],
    copyright: "© 2026 闪念 IdeaSnap. All rights reserved.",
  },
  en: {
    brand: "IdeaSnap",
    tagline: "AI Voice Notes",
    nav: [
      ["Features", "/features"],
      ["How it works", "/workflow"],
      ["Pricing", "/pricing"],
      ["Download", "/download"],
    ],
    download: "Free download",
    account: "Log in / Sign up",
    accountTitle: "Log in or create an IdeaSnap account on the official site",
    themeLight: "Switch to light mode",
    themeDark: "Switch to dark mode",
    language: "切换到中文",
    footerNote: "Speak. AI organizes. Built and maintained by indie developer Beicheng.",
    groups: [
      {
        title: "Product",
        links: [
          ["Desktop", "/desktop"],
          ["Mobile", "/mobile"],
          ["Apple Watch", "/watch"],
          ["Integrations & AI", "/integrations"],
        ],
      },
      {
        title: "Resources",
        links: [
          ["Feature overview", "/features"],
          ["How it works", "/workflow"],
          ["Download & install", "/download"],
          ["Help & FAQ", "/help"],
          ["Membership", "/pricing"],
        ],
      },
      {
        title: "About",
        links: [
          ["About IdeaSnap", "/about"],
          ["Contact", "/contact"],
          ["About Beicheng", externalLinks.developer],
          ["Changelog", externalLinks.updates],
        ],
      },
      {
        title: "Legal",
        links: [
          ["Privacy", "/privacy"],
          ["Terms", "/terms"],
        ],
      },
    ],
    copyright: "© 2026 IdeaSnap. All rights reserved.",
  },
} satisfies Record<Locale, object>;

export const homeCopy = {
  zh: {
    eyebrow: "Apple Watch、手机、电脑，随时接着记",
    titleMain: "想到什么，直接说。",
    titleAccent: "AI 自动整理成笔记和待办",
    description:
      "闪念把语音、图片和零散想法自动转写、总结、提取行动项。手机上随手记，电脑上继续写，多端协同不打断思路。",
    download: "免费下载",
    learn: "了解闪念",
    proof: ["App Store 编辑推荐", "曾进入效率榜前 5", "独立开发者持续维护"],
    aiDone: "已经整理完成",
    aiResult: "摘要、待办和标签",
    sync: "全平台同步",
    updated: "刚刚更新",
    featureKicker: "说完就得到",
    featureTitle: "不是把声音存起来，而是把想法整理好",
    featureLead: "你只负责表达，闪念把零散内容变成可以搜索、复盘和执行的笔记。",
    features: [
      ["清晰笔记", "口语自动变成可读内容", "自动生成标题、摘要与重点，省去手动整理。"],
      ["行动待办", "该做什么，不再遗漏", "从录音和笔记中识别行动项，后续推进更轻松。"],
      ["内容结构", "再零散的表达，也有条理", "段落、清单、分类与标签，让内容更容易被找到。"],
    ],
    workflowKicker: "一套自然的工作流",
    workflowTitle: "随时捕捉，回到桌面再深入整理",
    workflowLead: "手表和手机负责快速记录，电脑负责搜索、编辑与复盘。每台设备各做最适合的事。",
    workflowSteps: [
      ["随手记录", "走路、通勤、开会或睡前，抬腕或打开手机直接说。"],
      ["AI 自动处理", "自动转写、总结、提取待办，并为内容补充结构和标签。"],
      ["桌面继续推进", "回到电脑继续编辑、搜索和归档，让零碎输入成为长期积累。"],
    ],
    mobile: "移动端",
    multiSync: "多端同步",
    voiceNote: "语音记录",
    captured: "灵感已接住",
    autoOrganize: "自动整理",
    generated: "标题与待办已生成",
    phoneWatch: "手机与手表",
    mobileLine: "想到就说，随时捕捉",
    desktop: "桌面端",
    aiOrganized: "AI 已整理",
    tasks: "3 项待办已提取",
    desktopLine: "继续编辑、搜索与归档",
    tags: ["会议", "产品", "待跟进"],
    scenarioKicker: "真实使用场景",
    scenarioTitle: "灵感来得不按时间表，闪念随时接住",
    scenarios: [
      ["会议复盘", "整理重点、结论与待办，减少会后补笔记的负担。", "meeting"],
      ["腕上灵感", "想法出现时先说下来，不用解锁手机，也不用找纸笔。", "watch"],
      ["阅读摘记", "把内容和理解一起记录，整理成可搜索的知识卡片。", "reading"],
      ["写作素材", "先收集零散观点，再在桌面端筛选、改写和延展。", "writing"],
    ],
    downloadKicker: "全平台可用",
    downloadTitle: "一个闪念账号，覆盖你的所有设备",
    downloadLead: "Apple Watch、iOS、Android、Windows、macOS 与 Linux，让记录和整理自然接续。",
    downloadDetails: "查看全部平台与安装说明",
    pricingKicker: "简单透明的价格",
    pricingTitle: "选择适合你的方案",
    pricingLead: "一处订阅，全平台同步会员权益。自动续费可随时取消。",
    plans: [
      ["灵活体验", "月度订阅", "¥18", "/ 月", "适合先体验完整工作流"],
      ["推荐方案", "年度订阅", "¥128", "/ 年", "相比月付更适合长期记录"],
      ["限时早鸟", "终身买断", "实时价格", "一次性", "一次购买，长期使用"],
    ],
    planAction: "查看方案详情",
    trustKicker: "认真对待每一条记录",
    trustTitle: "专注记录与整理，也认真对待隐私",
    trustLead: "闪念不做复杂的 All-in-one 知识库，只把「更快记录、更好整理」这件事持续做好。",
    privacy: "了解隐私保护",
    trustPoints: [
      ["由独立开发者北城长期维护", "持续更新，优先解决真实用户遇到的问题。"],
      ["不出售个人数据", "不依靠隐私数据获利，不用于广告画像。"],
      ["AI 功能由你决定", "明确同意后才使用，并可根据需要关闭。"],
    ],
    finalLabel: "闪念 AI 语音笔记",
    finalTitle: "从下一句灵感开始",
    finalLead: "手机负责捕捉，电脑负责整理，让想法自然长成一份清晰笔记。",
  },
  en: {
    eyebrow: "Apple Watch, phone, and desktop — keep the thought moving",
    titleMain: "Say it when it comes.",
    titleAccent: "AI turns it into notes and tasks",
    description:
      "IdeaSnap transcribes voice, images, and scattered thoughts, then creates summaries and action items. Capture on mobile and continue on desktop without breaking your flow.",
    download: "Free download",
    learn: "Explore IdeaSnap",
    proof: ["App Store Editors’ Choice", "Top 5 in Productivity", "Continuously maintained"],
    aiDone: "Organization complete",
    aiResult: "Summary, tasks, and tags",
    sync: "Cross-platform sync",
    updated: "Updated just now",
    featureKicker: "Ready when you finish speaking",
    featureTitle: "Not just stored audio — a thought you can use",
    featureLead: "You express the idea. IdeaSnap turns it into searchable, reviewable, actionable notes.",
    features: [
      ["Clear notes", "Speech becomes readable content", "Generate titles, summaries, and key points automatically."],
      ["Action items", "Never lose the next step", "Identify tasks from recordings and notes so work keeps moving."],
      ["Useful structure", "Even scattered thoughts gain shape", "Paragraphs, lists, categories, and tags make ideas easy to find."],
    ],
    workflowKicker: "A natural workflow",
    workflowTitle: "Capture anywhere, organize deeply on desktop",
    workflowLead: "Watch and phone handle quick capture. Desktop handles search, editing, and review. Each device does what it does best.",
    workflowSteps: [
      ["Capture quickly", "Raise your wrist or open your phone while walking, commuting, meeting, or before sleep."],
      ["Let AI process it", "Transcribe, summarize, extract tasks, and add helpful structure and tags."],
      ["Continue on desktop", "Edit, search, and archive on your computer so fragments become long-term knowledge."],
    ],
    mobile: "Mobile",
    multiSync: "Live sync",
    voiceNote: "Voice capture",
    captured: "Thought captured",
    autoOrganize: "AI organization",
    generated: "Title and tasks created",
    phoneWatch: "Phone & Watch",
    mobileLine: "Speak the moment it arrives",
    desktop: "Desktop",
    aiOrganized: "AI organized",
    tasks: "3 action items found",
    desktopLine: "Edit, search, and archive",
    tags: ["Meeting", "Product", "Follow-up"],
    scenarioKicker: "Built for real moments",
    scenarioTitle: "Ideas ignore schedules. IdeaSnap stays ready.",
    scenarios: [
      ["Meeting recap", "Turn discussion into key points, decisions, and action items.", "meeting"],
      ["Wrist inspiration", "Speak the thought without reaching for your phone.", "watch"],
      ["Reading notes", "Capture the source and your interpretation as searchable cards.", "reading"],
      ["Writing material", "Collect fragments, then refine and expand them on desktop.", "writing"],
    ],
    downloadKicker: "Available everywhere",
    downloadTitle: "One account across all your devices",
    downloadLead: "Apple Watch, iOS, Android, Windows, macOS, and Linux keep capture and organization connected.",
    downloadDetails: "All platforms & install guide",
    pricingKicker: "Simple, transparent pricing",
    pricingTitle: "Choose the plan that fits",
    pricingLead: "One membership syncs across every platform. Auto-renewal can be cancelled anytime.",
    plans: [
      ["Flexible", "Monthly", "¥18", "/ month", "A simple way to try the complete workflow"],
      ["Recommended", "Yearly", "¥128", "/ year", "Better value for a long-term note habit"],
      ["Early bird", "Lifetime", "Live price", "one time", "Buy once and use it long-term"],
    ],
    planAction: "See plan details",
    trustKicker: "Every note deserves care",
    trustTitle: "Focused on capture, serious about privacy",
    trustLead: "IdeaSnap does not chase an all-in-one workspace. It stays focused on faster capture and better organization.",
    privacy: "How privacy works",
    trustPoints: [
      ["Maintained by indie developer Beicheng", "Ongoing updates shaped around real user problems."],
      ["Personal data is not sold", "The business is not built on advertising profiles."],
      ["You control AI", "AI is used only after explicit consent and can be disabled."],
    ],
    finalLabel: "IdeaSnap AI Voice Notes",
    finalTitle: "Start with your next thought",
    finalLead: "Capture on mobile, organize on desktop, and let one sentence grow into a clear note.",
  },
};

const zhPages: Record<PageKey, DetailCopy> = {
  features: {
    group: "产品 · 功能总览",
    title: "从开口记录，到得到一份能继续使用的笔记",
    lead: "闪念不是录音仓库。它围绕捕捉、转写、整理、搜索和继续创作，形成一套完整但不打扰思路的笔记流程。",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-hero.webp",
    heroAlt: "闪念全平台真实产品界面",
    primary: { label: "查看使用方法", href: "/workflow" },
    secondary: { label: "下载闪念", href: "/download" },
    highlights: [
      { value: "语音优先", label: "想到就说" },
      { value: "AI 整理", label: "标题、摘要、待办" },
      { value: "全平台", label: "从手表到桌面" },
    ],
    sections: [
      {
        id: "capture",
        eyebrow: "01 · 捕捉",
        title: "不必先想好格式，把原始想法留住",
        body: "走路、通勤、会中或睡前，用手机长按麦克风或抬腕开始录音。语音、图片和附件可以一起保存，先减少输入阻力，再留到合适的设备上整理。",
        bullets: ["长按麦克风快速录音", "图片与附件随笔记保存", "手机与 Apple Watch 都能接住灵感"],
        image: "https://ideasnap.xyz/assets/showcase/mobile-device-ios.webp",
        imageAlt: "闪念手机端记录界面",
        actions: [{ label: "深入了解手机端", href: "/mobile" }],
      },
      {
        id: "organize",
        eyebrow: "02 · 整理",
        title: "AI 把口语变成更容易阅读和推进的内容",
        body: "完成记录后，闪念可以转写语音、提炼主题与摘要、识别行动项，并用标题、段落、清单和标签补充结构。原始想法仍然是核心，AI 负责减少整理成本。",
        bullets: ["语音自动转文字", "自动总结与提取重点", "识别待办并补充结构"],
        image: "https://ideasnap.xyz/assets/showcase/desktop-light-device.webp",
        imageAlt: "闪念 AI 整理后的桌面笔记",
        actions: [{ label: "了解联动与 AI", href: "/integrations" }],
      },
      {
        id: "retrieve",
        eyebrow: "03 · 找回",
        title: "搜索、标签与分类，让过去的想法重新出现",
        body: "记录的价值不在数量，而在需要时能重新找到。你可以通过关键词、标签和分类筛选内容，在电脑上继续编辑，把零碎输入变成长期可复用的材料。",
        bullets: ["关键词搜索", "标签筛选与分类", "桌面端深度编辑和归档"],
        actions: [{ label: "深入了解桌面端", href: "/desktop" }],
      },
    ],
    related: ["workflow", "mobile", "desktop"],
  },
  workflow: {
    group: "使用方法",
    title: "先说出来，再把它推进成结果",
    lead: "参考真实使用节奏，闪念把一条想法分成捕捉、AI 处理和桌面推进三个阶段。你不需要一次完成所有整理。",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-illustration.webp",
    heroAlt: "闪念从移动端到桌面端的工作流",
    primary: { label: "开始下载", href: "/download" },
    secondary: { label: "功能总览", href: "/features" },
    highlights: [
      { value: "1", label: "随手记录" },
      { value: "2", label: "AI 处理" },
      { value: "3", label: "桌面推进" },
    ],
    sections: [
      {
        id: "quick-start",
        eyebrow: "第 1 步",
        title: "在最方便的设备上快速记录",
        body: "走路或运动时用 Apple Watch，通勤或会中用手机。轻点或长按麦克风开始说，不需要先排版，也不必先决定分类。",
        bullets: ["说出背景、判断和下一步", "需要时附上图片或材料", "先完整表达，再结束录音"],
        actions: [
          { label: "手机端方法", href: "/mobile" },
          { label: "手表端方法", href: "/watch" },
        ],
      },
      {
        id: "ai-process",
        eyebrow: "第 2 步",
        title: "让 AI 完成机械整理",
        body: "在你主动使用并同意后，AI 会转写语音、生成标题和摘要、提取待办，并把口语整理成更适合阅读的结构。你可以继续检查和编辑结果。",
        bullets: ["转写与修正文稿", "提炼重点和摘要", "识别行动项与标签"],
        actions: [{ label: "AI 与隐私说明", href: "/integrations" }],
      },
      {
        id: "desktop-finish",
        eyebrow: "第 3 步",
        title: "回到桌面完成搜索、编辑与归档",
        body: "电脑端适合处理长笔记、会议复盘和写作素材。搜索相关内容、核对待办、补充细节，再按标签和分类归档。",
        bullets: ["会议：整理结论和负责人", "阅读：记录来源与自己的理解", "写作：筛选素材并扩展成文章或方案"],
        image: "https://ideasnap.xyz/assets/showcase/windows-illustration.webp",
        imageAlt: "闪念桌面端整理界面",
        actions: [{ label: "桌面端能力", href: "/desktop" }],
      },
      {
        id: "scenarios",
        eyebrow: "典型场景",
        title: "会议、灵感、阅读和写作都从同一条路径开始",
        body: "会议结束后得到重点和待办；灵感出现时在腕上先记；阅读时保存摘录和理解；写作时把零散观点集中到桌面端继续展开。",
        bullets: ["会议复盘", "腕上灵感", "阅读摘记", "写作素材"],
      },
    ],
    related: ["features", "watch", "desktop"],
  },
  pricing: {
    group: "会员与价格",
    title: "同一份会员权益，在所有设备上同步",
    lead: "月度适合先体验，年度适合长期记录，终身版适合确定留下的用户。最终金额与税费以 Waffo 正式收银台为准。",
    heroImage: "https://ideasnap.xyz/assets/showcase/desktop-light-device.webp",
    heroAlt: "闪念桌面端会员体验",
    primary: { label: "前往安全购买", href: externalLinks.checkout, external: true },
    secondary: { label: "先查看功能", href: "/features" },
    highlights: [
      { value: "¥18", label: "月度" },
      { value: "¥128", label: "年度" },
      { value: "实时价格", label: "终身早鸟" },
    ],
    sections: [
      {
        id: "monthly",
        eyebrow: "灵活体验",
        title: "月度订阅 · ¥18 / 月",
        body: "适合希望先完整体验语音记录、AI 整理和多端同步的用户。自动续费可按支付渠道规则取消。",
        bullets: ["无限语音记录", "AI 智能总结", "待办自动提取", "全平台同步"],
        actions: [{ label: "选择月付", href: externalLinks.checkout, external: true }],
      },
      {
        id: "yearly",
        eyebrow: "推荐方案",
        title: "年度订阅 · ¥128 / 年",
        body: "包含月度方案的完整权益，更适合已经形成记录习惯、希望长期积累的用户。",
        bullets: ["包含月度全部权益", "按年购买更划算", "优先功能更新", "全平台会员同步"],
        actions: [{ label: "选择年付", href: externalLinks.checkout, external: true }],
      },
      {
        id: "lifetime",
        eyebrow: "限时早鸟",
        title: "终身买断 · 以 Waffo 实时价格为准",
        body: "一次购买，长期使用核心能力。早鸟价格可能调整，实际金额以正式收银台显示为准。",
        bullets: ["一次购买，长期使用", "包含核心 AI 能力", "优先功能更新", "全平台会员同步"],
        actions: [{ label: "选择终身版", href: externalLinks.checkout, external: true }],
      },
    ],
    related: ["features", "download", "terms"],
  },
  download: {
    group: "资源 · 下载与安装",
    title: "在手表、手机和电脑上继续同一条笔记",
    lead: "当前版本 1.0.18。下面列出官方安装包和首次安装提示，避免系统安全提示打断使用。",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-illustration.webp",
    heroAlt: "闪念支持的全平台设备",
    primary: { label: "iOS / Apple Watch", href: externalLinks.appStore, external: true },
    secondary: { label: "Android APK", href: externalLinks.android, external: true },
    highlights: [
      { value: "1.0.18", label: "当前版本" },
      { value: "6 类", label: "支持平台" },
      { value: "同账号", label: "会员与笔记同步" },
    ],
    sections: [
      {
        id: "mobile-packages",
        eyebrow: "移动端",
        title: "iPhone、iPad、Apple Watch 与 Android",
        body: "iOS、iPadOS 与 Apple Watch 通过 App Store 安装；Android 使用官方 APK。Apple Watch 随 iOS 版本提供。",
        bullets: ["iOS / iPadOS / Watch：App Store", "Android：官方 APK", "同一账号同步笔记和会员"],
        actions: [
          { label: "前往 App Store", href: externalLinks.appStore, external: true },
          { label: "下载 Android APK", href: externalLinks.android, external: true },
        ],
      },
      {
        id: "desktop-packages",
        eyebrow: "桌面端",
        title: "Windows、macOS 与 Linux",
        body: "Windows 提供安装版与便携版；macOS 提供 DMG；Linux 提供 DEB 与 AppImage。请选择符合当前设备的安装包。",
        bullets: ["Windows：Setup / Portable", "macOS：DMG", "Linux：DEB / AppImage"],
        actions: [
          { label: "Windows Setup", href: externalLinks.windowsSetup, external: true },
          { label: "macOS DMG", href: externalLinks.macos, external: true },
          { label: "Linux DEB", href: externalLinks.linuxDeb, external: true },
        ],
      },
      {
        id: "install",
        eyebrow: "首次安装",
        title: "遇到系统安全提示时怎么做",
        body: "闪念是经过代码签名的正式应用。由于分发渠道不同，macOS、Android、Windows 或 Linux 首次运行时可能出现系统保护提示。",
        bullets: ["macOS：系统设置 → 隐私与安全性 → 仍要打开", "Android：允许来自当前来源的应用", "Windows：更多信息 → 仍要运行", "Linux AppImage：先赋予可执行权限"],
        actions: [{ label: "查看常见问题", href: "/help" }],
      },
    ],
    related: ["mobile", "desktop", "help"],
  },
  mobile: {
    group: "产品 · 手机端",
    title: "开口即记录，口袋里的闪念",
    lead: "iPhone、iPad 与 Android 均可使用。适合通勤、会中、睡前——想法出现时先说出来，之后再整理。",
    heroImage: "https://ideasnap.xyz/assets/showcase/mobile-device-ios.webp",
    heroAlt: "闪念 iOS 端真实界面",
    primary: { label: "前往 App Store", href: externalLinks.appStore, external: true },
    secondary: { label: "Android APK", href: externalLinks.android, external: true },
    highlights: [
      { value: "长按", label: "快速录音" },
      { value: "图片", label: "附件一起保存" },
      { value: "同步", label: "手表与桌面" },
    ],
    sections: [
      {
        id: "record",
        eyebrow: "快速输入",
        title: "长按麦克风，先把完整想法说出来",
        body: "无需创建文档或挑选模板。打开闪念后直接开始录音，适合不方便打字、又不想让灵感溜走的时刻。",
        bullets: ["语音快速记录", "支持图片与附件", "会中、通勤和睡前都能使用"],
        image: "https://ideasnap.xyz/assets/showcase/mobile-device-android.webp",
        imageAlt: "闪念 Android 端真实界面",
      },
      {
        id: "browse",
        eyebrow: "浏览与找回",
        title: "用卡片、标签和搜索整理日常记录",
        body: "记录完成后可以用卡片浏览，通过标签筛选或关键词搜索重新找到内容。需要深度编辑时，再回到电脑继续。",
        bullets: ["卡片浏览", "标签筛选", "关键词搜索", "跨端继续编辑"],
      },
      {
        id: "sync",
        eyebrow: "连续使用",
        title: "与 Apple Watch 和桌面端使用同一套笔记",
        body: "手机是手表记录与桌面整理之间的桥梁。同一个闪念账号会同步内容和会员权益，让输入和整理自然接续。",
        actions: [
          { label: "了解手表端", href: "/watch" },
          { label: "了解桌面端", href: "/desktop" },
        ],
      },
    ],
    related: ["watch", "workflow", "download"],
  },
  watch: {
    group: "产品 · Apple Watch",
    title: "抬腕就能记，灵感不等手机",
    lead: "Apple Watch 端支持准备录音、录音中控制与查看笔记卡片。走路、运动、临时会议时，先把想法留下来。",
    heroImage: "https://ideasnap.xyz/assets/showcase/watch-device.webp",
    heroAlt: "闪念 Apple Watch 设备展示",
    primary: { label: "随 iOS 版安装", href: externalLinks.appStore, external: true },
    secondary: { label: "了解手机端", href: "/mobile" },
    highlights: [
      { value: "抬腕", label: "准备录音" },
      { value: "轻点", label: "暂停与结束" },
      { value: "回到桌面", label: "继续整理" },
    ],
    sections: [
      {
        id: "start",
        eyebrow: "腕上工作流",
        title: "抬腕准备，轻点开始录音",
        body: "不方便拿手机时，直接从手表开始。适合走路、运动、临时会议或任何需要双手保持自由的场景。",
        bullets: ["快速进入准备录音状态", "轻点开始", "查看已有笔记卡片"],
        image: "https://ideasnap.xyz/assets/showcase/watch-illustration.webp",
        imageAlt: "闪念手表端界面",
      },
      {
        id: "control",
        eyebrow: "录音控制",
        title: "在手腕上暂停或结束，再交给 AI 整理",
        body: "录音过程中可以暂停或结束，关键语音会保存下来。回到手机或桌面后，继续转写、总结、提取待办和编辑。",
        bullets: ["暂停与继续", "结束后自动进入后续流程", "与手机和桌面同步"],
      },
      {
        id: "install",
        eyebrow: "安装说明",
        title: "手表端随 iOS 版一起提供",
        body: "在 iPhone 上安装闪念后，即可根据 Apple Watch 的应用安装设置使用手表端。笔记与账号权益保持一致。",
        actions: [{ label: "查看下载与安装", href: "/download" }],
      },
    ],
    related: ["mobile", "workflow", "download"],
  },
  desktop: {
    group: "产品 · 桌面端",
    title: "在电脑上把灵感整理成长期笔记",
    lead: "会议复盘、长文整理、搜索归档——桌面端适合深度工作。支持 Windows、macOS、Linux，也支持浅色与深色界面。",
    heroImage: "https://ideasnap.xyz/assets/showcase/windows-illustration.webp",
    heroAlt: "闪念桌面端真实界面",
    primary: { label: "前往下载", href: "/download" },
    secondary: { label: "查看工作流", href: "/workflow" },
    highlights: [
      { value: "搜索", label: "快速找回" },
      { value: "编辑", label: "处理长笔记" },
      { value: "浅色 / 深色", label: "跟随使用环境" },
    ],
    sections: [
      {
        id: "deep-work",
        eyebrow: "深度整理",
        title: "处理会议录音和长文本，不被小屏限制",
        body: "在更大的屏幕上阅读 AI 摘要、核对待办、修订转写结果并补充细节。适合会后复盘、写作和长期归档。",
        bullets: ["阅读 AI 总结", "核对与编辑行动项", "整理长文本和写作素材"],
        image: "https://ideasnap.xyz/assets/showcase/desktop-light-device.webp",
        imageAlt: "闪念桌面端浅色模式",
      },
      {
        id: "find",
        eyebrow: "搜索与归档",
        title: "用搜索、标签和分类建立可找回的积累",
        body: "通过关键词搜索、标签筛选和分类管理，将来自手机与手表的零碎输入重新组织成可以复用的内容。",
        bullets: ["关键词搜索", "标签筛选", "分类与归档", "同账号跨端同步"],
      },
      {
        id: "themes",
        eyebrow: "界面体验",
        title: "浅色和深色模式，适应不同工作环境",
        body: "白天使用浅色界面，夜间切换深色界面。官网现在也恢复了亮暗色切换，让产品体验从介绍页到客户端保持一致。",
        image: "https://ideasnap.xyz/assets/showcase/desktop-dark-device.webp",
        imageAlt: "闪念桌面端深色模式",
      },
      {
        id: "platforms",
        eyebrow: "平台",
        title: "Windows、macOS 与 Linux",
        body: "Windows 提供安装版与便携版，macOS 提供 DMG，Linux 提供 DEB 与 AppImage。首次安装提示可在下载页查看。",
        actions: [{ label: "选择桌面安装包", href: "/download#desktop-packages" }],
      },
    ],
    related: ["workflow", "download", "mobile"],
  },
  integrations: {
    group: "产品 · 联动与 AI",
    title: "整理想法，也能接进你的工作流",
    lead: "闪念用 AI 帮助转写、总结与提取待办，并支持 Notion 联动。AI 功能需你明确同意，也可随时关闭。",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-illustration.webp",
    heroAlt: "闪念全平台与工作流示意",
    primary: { label: "下载闪念", href: "/download" },
    secondary: { label: "隐私说明", href: "/privacy" },
    highlights: [
      { value: "转写", label: "语音变文字" },
      { value: "总结", label: "重点与结构" },
      { value: "Notion", label: "授权联动" },
    ],
    sections: [
      {
        id: "ai",
        eyebrow: "AI 整理",
        title: "只有在你主动使用并明确同意后才调用 AI",
        body: "为提供语音转文字、智能整理与内容分析，闪念目前可能使用豆包、OpenAI GPT、通义千问等第三方 AI 服务。你可以在设置中关闭相关能力。",
        bullets: ["首次使用需明确同意", "可在设置中关闭 AI", "内容不用于广告画像或出售", "内容不用于训练第三方模型"],
        actions: [{ label: "查看完整隐私说明", href: "/privacy" }],
      },
      {
        id: "notion",
        eyebrow: "Notion 联动",
        title: "通过 Notion 授权，把闪念接入现有整理方式",
        body: "完成 Notion 授权后，浏览器会返回闪念应用继续后续流程。请确保设备上已经安装闪念客户端。",
        bullets: ["使用 Notion 官方授权", "保留 /notion/callback/ 回调路径", "授权完成后通过原 Scheme 返回客户端", "可随时在相应服务中管理授权"],
      },
      {
        id: "account",
        eyebrow: "账号与同步",
        title: "网站购买的会员权益同步到所有客户端",
        body: "使用同一个闪念账号登录，网站、手机、手表和桌面端会共享会员权益。Web 支付通过 Waffo 安全收银台完成。",
        actions: [
          { label: "查看会员方案", href: "/pricing" },
          { label: "阅读服务条款", href: "/terms" },
        ],
      },
    ],
    related: ["features", "privacy", "workflow"],
  },
  help: {
    group: "资源 · 帮助",
    title: "快速上手与常见问题",
    lead: "从第一次录音到多端同步，再到安装、会员和隐私问题，这里给出可以直接照着做的答案。",
    heroImage: "https://ideasnap.xyz/assets/showcase/mobile-device-ios.webp",
    heroAlt: "闪念手机端笔记界面",
    primary: { label: "查看使用方法", href: "/workflow" },
    secondary: { label: "联系我们", href: "/contact" },
    highlights: [
      { value: "1", label: "安装并登录" },
      { value: "2", label: "说出第一条" },
      { value: "3", label: "检查 AI 结果" },
    ],
    sections: [
      {
        id: "getting-started",
        eyebrow: "快速上手",
        title: "第一次使用，按这三步开始",
        body: "在常用设备上安装并登录；打开手机或手表录制第一条想法；等待转写与整理完成，再检查标题、摘要和待办。需要长时间编辑时回到桌面端。",
        bullets: ["安装并使用同一账号登录", "长按麦克风说出想法", "核对 AI 结果并补充标签"],
      },
      {
        id: "install-faq",
        eyebrow: "安装问题",
        title: "首次启动被系统拦截怎么办？",
        body: "macOS 可在系统设置的隐私与安全性中选择仍要打开；Android 按提示允许当前来源；Windows 在 SmartScreen 中选择更多信息后仍要运行。",
        actions: [{ label: "查看完整安装说明", href: "/download#install" }],
      },
      {
        id: "account-faq",
        eyebrow: "账号与会员",
        title: "网站购买的会员会同步吗？",
        body: "会。只要各端登录同一个闪念账号，会员权益会同步到 iPhone、iPad、Apple Watch、Android、macOS、Windows 与 Linux。取消订阅和退款规则以支付渠道与服务条款为准。",
        actions: [{ label: "查看服务条款", href: "/terms" }],
      },
      {
        id: "privacy-faq",
        eyebrow: "AI 与隐私",
        title: "内容会被用于训练吗？",
        body: "不会用于训练第三方模型，也不会出售或用于广告画像。AI 功能需要明确同意，并可以关闭。",
        actions: [{ label: "查看隐私说明", href: "/privacy" }],
      },
    ],
    related: ["workflow", "download", "contact"],
  },
  about: {
    group: "关于",
    title: "关于闪念",
    lead: "闪念是一款 AI 语音笔记应用，帮助你接住一闪而过的想法，并自动整理成可以继续行动的内容。",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-hero.webp",
    heroAlt: "闪念在不同设备上的产品全貌",
    primary: { label: "了解产品功能", href: "/features" },
    secondary: { label: "认识开发者北城", href: externalLinks.developer, external: true },
    highlights: [
      { value: "2018", label: "产品开始" },
      { value: "2025", label: "App Store 编辑推荐" },
      { value: "15+", label: "产品本地化语言" },
    ],
    sections: [
      {
        id: "origin",
        eyebrow: "产品起源",
        title: "从 2018 年左右开始，持续更新至今",
        body: "闪念长期保持迭代，并在 2025 年 11 月获得 App Store 编辑推荐。2026 年 1 月的 3.5 版本加入 AI 总结能力。比堆叠功能更重要的是，真正帮助用户解决记录与整理问题。",
        bullets: ["持续的小版本与阶段性大更新", "曾进入效率类榜单前列", "围绕真实使用反馈打磨"],
      },
      {
        id: "developer",
        eyebrow: "谁在维护",
        title: "由独立开发者北城长期打造",
        body: "闪念不是一次性的产品实验。它由独立开发者北城持续开发和维护，重视细节、本地化和长期可依赖的使用体验。",
        actions: [
          { label: "查看开发日志", href: externalLinks.updates, external: true },
          { label: "关于北城", href: externalLinks.developer, external: true },
        ],
      },
      {
        id: "focus",
        eyebrow: "我们在意什么",
        title: "专注语音捕捉与 AI 整理，不做复杂的 All-in-one",
        body: "持续更新、隐私优先、克制的功能边界，以及让不同语言和设备上的用户都能顺畅使用，是闪念长期坚持的方向。",
        bullets: ["持续更新，让产品保持生命力", "重视细节与 15+ 语言本地化", "隐私优先，不做不必要的数据收集", "聚焦记录与整理"],
      },
    ],
    related: ["features", "privacy", "contact"],
  },
  contact: {
    group: "关于 · 联系",
    title: "把问题、建议或合作想法告诉我们",
    lead: "产品问题、合作想法，或只是想打个招呼，都可以通过下面的渠道联系。每条反馈都会认真阅读。",
    heroImage: "https://ideasnap.xyz/assets/icons/Appicon.png",
    heroAlt: "闪念应用图标",
    primary: { label: "发送邮件", href: "mailto:506343891@qq.com", external: true },
    secondary: { label: "查看常见问题", href: "/help" },
    highlights: [
      { value: "邮箱", label: "506343891@qq.com" },
      { value: "微信", label: "shine5211314" },
      { value: "GitHub", label: "northcity" },
    ],
    sections: [
      {
        id: "channels",
        eyebrow: "联系渠道",
        title: "选择最方便的方式",
        body: "产品反馈优先使用邮件，方便附带设备、系统版本和问题截图；也可以通过社交平台了解独立开发动态。",
        actions: [
          { label: "邮箱", href: "mailto:506343891@qq.com", external: true },
          { label: "X / Twitter", href: "https://x.com/chenxi44779232", external: true },
          { label: "GitHub", href: "https://github.com/northcity", external: true },
          { label: "小红书", href: "https://xhslink.com/m/7ELB1JL5RId", external: true },
        ],
      },
      {
        id: "feedback",
        eyebrow: "问题与建议",
        title: "报告问题时，最好附上这些信息",
        body: "请说明使用平台、系统版本、闪念版本、问题出现前后的操作，以及是否可以稳定复现。信息越完整，越容易快速定位。",
        bullets: ["设备和操作系统", "闪念版本号", "复现步骤", "不含敏感内容的截图或录屏"],
      },
      {
        id: "collaboration",
        eyebrow: "合作",
        title: "有意义的合作项目，欢迎邮件沟通",
        body: "请在邮件中简要说明项目背景、合作方式、时间计划和双方能创造的价值，便于判断是否适合继续讨论。",
      },
    ],
    related: ["help", "about", "features"],
  },
  privacy: {
    group: "法律 · 隐私说明",
    title: "AI 帮你整理，但控制权始终在你",
    lead: "这是一份便于阅读的隐私摘要。具体法律条款与数据处理规则，以正式隐私政策为准。",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-illustration.webp",
    heroAlt: "闪念全平台与隐私保护示意",
    primary: { label: "阅读正式隐私政策", href: externalLinks.privacy, external: true },
    secondary: { label: "了解联动与 AI", href: "/integrations" },
    highlights: [
      { value: "明确同意", label: "才启用 AI" },
      { value: "可关闭", label: "由你决定" },
      { value: "不出售", label: "不做广告画像" },
    ],
    sections: [
      {
        id: "consent",
        eyebrow: "AI 使用",
        title: "首次使用 AI 能力时，需要你明确同意",
        body: "只有在你主动使用语音转写、智能整理或相关能力时，闪念才会按功能需要调用第三方 AI 服务。相关功能可以在设置中关闭。",
        bullets: ["首次使用需明确同意", "可在设置中关闭", "只在提供相应功能时处理"],
      },
      {
        id: "data",
        eyebrow: "数据原则",
        title: "不出售个人数据，不用于广告画像",
        body: "闪念的商业模式依靠会员付费，而不是出售用户数据。内容不会用于训练第三方模型。",
        bullets: ["不出售个人数据", "不用于广告画像", "不用于训练第三方模型"],
      },
      {
        id: "official",
        eyebrow: "正式条款",
        title: "需要法律层面的完整信息，请阅读正式政策",
        body: "本页用于帮助理解重点，不替代正式隐私政策。涉及数据类型、处理目的、第三方服务和你的权利时，以正式版本为准。",
        actions: [{ label: "打开正式隐私政策", href: externalLinks.privacy, external: true }],
      },
    ],
    related: ["integrations", "terms", "contact"],
  },
  terms: {
    group: "法律 · 服务条款",
    title: "关于会员、续费、取消与使用规则",
    lead: "这是一份便于阅读的服务摘要。最终购买、取消、退款和账号规则，以正式服务条款及对应支付渠道规则为准。",
    heroImage: "https://ideasnap.xyz/assets/showcase/desktop-light-device.webp",
    heroAlt: "闪念桌面端产品界面",
    primary: { label: "阅读正式服务条款", href: externalLinks.terms, external: true },
    secondary: { label: "查看会员方案", href: "/pricing" },
    highlights: [
      { value: "月 / 年", label: "自动续费方案" },
      { value: "可取消", label: "按渠道管理" },
      { value: "同账号", label: "权益跨端同步" },
    ],
    sections: [
      {
        id: "membership",
        eyebrow: "会员权益",
        title: "同一闪念账号共享会员权益",
        body: "在网站或支持的应用内完成购买后，使用同一个账号登录各客户端，会员权益会在支持的平台间同步。",
      },
      {
        id: "renewal",
        eyebrow: "续费与取消",
        title: "自动续费可按原支付渠道管理",
        body: "Apple、Google 或网站购买的订阅，需要在相应渠道中管理。取消后通常可以继续使用到当前计费周期结束，具体以渠道规则为准。",
      },
      {
        id: "refund",
        eyebrow: "退款与最终金额",
        title: "价格、税费和退款规则以正式页面为准",
        body: "价格可能随活动或渠道调整，最终金额以结算页显示为准。退款资格与时限受正式服务条款和支付渠道规则约束。",
        actions: [{ label: "查看正式服务条款", href: externalLinks.terms, external: true }],
      },
    ],
    related: ["pricing", "privacy", "help"],
  },
};

const enPages: Record<PageKey, DetailCopy> = {
  features: {
    group: "Product · Feature overview",
    title: "From spoken thought to a note you can keep using",
    lead: "IdeaSnap is not an audio archive. It connects capture, transcription, organization, retrieval, and continued writing in one focused workflow.",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-hero.webp",
    heroAlt: "IdeaSnap across watch, mobile, and desktop",
    primary: { label: "See how it works", href: "/workflow" },
    secondary: { label: "Download IdeaSnap", href: "/download" },
    highlights: [
      { value: "Voice-first", label: "Speak naturally" },
      { value: "AI organized", label: "Title, summary, tasks" },
      { value: "Cross-platform", label: "Watch to desktop" },
    ],
    sections: [
      {
        id: "capture",
        eyebrow: "01 · Capture",
        title: "Keep the raw thought before worrying about structure",
        body: "On a walk, commute, in a meeting, or before sleep, hold the microphone on mobile or raise your wrist to record. Voice, images, and attachments can stay together until you are ready to organize.",
        bullets: ["Fast voice capture", "Images and attachments", "Capture from phone or Apple Watch"],
        image: "https://ideasnap.xyz/assets/showcase/mobile-device-ios.webp",
        imageAlt: "IdeaSnap mobile capture interface",
        actions: [{ label: "Explore mobile", href: "/mobile" }],
      },
      {
        id: "organize",
        eyebrow: "02 · Organize",
        title: "AI turns speech into content that is easier to read and act on",
        body: "After capture, IdeaSnap can transcribe voice, extract themes and summaries, identify action items, and add helpful structure with titles, lists, and tags.",
        bullets: ["Speech-to-text", "Automatic summaries", "Action items and structure"],
        image: "https://ideasnap.xyz/assets/showcase/desktop-light-device.webp",
        imageAlt: "IdeaSnap organized note on desktop",
        actions: [{ label: "AI & integrations", href: "/integrations" }],
      },
      {
        id: "retrieve",
        eyebrow: "03 · Retrieve",
        title: "Search, tags, and categories bring older ideas back",
        body: "A note matters when it can be found again. Search by keyword, filter with tags and categories, then continue editing on desktop so fragments become reusable material.",
        bullets: ["Keyword search", "Tags and categories", "Desktop editing and archive"],
        actions: [{ label: "Explore desktop", href: "/desktop" }],
      },
    ],
    related: ["workflow", "mobile", "desktop"],
  },
  workflow: {
    group: "How it works",
    title: "Say it first, then move it toward an outcome",
    lead: "IdeaSnap follows real-life rhythm: capture, AI processing, and desktop follow-through. You do not have to finish every part in one sitting.",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-illustration.webp",
    heroAlt: "IdeaSnap workflow from mobile to desktop",
    primary: { label: "Start downloading", href: "/download" },
    secondary: { label: "Feature overview", href: "/features" },
    highlights: [
      { value: "1", label: "Quick capture" },
      { value: "2", label: "AI processing" },
      { value: "3", label: "Desktop follow-through" },
    ],
    sections: [
      {
        id: "quick-start",
        eyebrow: "Step 1",
        title: "Capture on the device that is already with you",
        body: "Use Apple Watch while walking or exercising, and mobile during a commute or meeting. Tap or hold the microphone and speak without choosing a template first.",
        bullets: ["Include context, judgment, and next step", "Attach an image when useful", "Finish the thought before ending"],
        actions: [
          { label: "Mobile guide", href: "/mobile" },
          { label: "Watch guide", href: "/watch" },
        ],
      },
      {
        id: "ai-process",
        eyebrow: "Step 2",
        title: "Let AI handle mechanical organization",
        body: "With your explicit consent, AI can transcribe, title, summarize, extract tasks, and structure the spoken content. You can still review and edit the result.",
        bullets: ["Transcription and cleanup", "Key points and summary", "Tasks and tags"],
        actions: [{ label: "AI & privacy", href: "/integrations" }],
      },
      {
        id: "desktop-finish",
        eyebrow: "Step 3",
        title: "Finish searching, editing, and archiving on desktop",
        body: "Desktop is better for long notes, meeting reviews, and writing material. Find related ideas, verify tasks, add context, and archive with tags and categories.",
        bullets: ["Meetings: decisions and owners", "Reading: source plus your interpretation", "Writing: expand fragments into a draft"],
        image: "https://ideasnap.xyz/assets/showcase/windows-illustration.webp",
        imageAlt: "IdeaSnap desktop workspace",
        actions: [{ label: "Desktop capabilities", href: "/desktop" }],
      },
      {
        id: "scenarios",
        eyebrow: "Common scenarios",
        title: "Meetings, inspiration, reading, and writing share one path",
        body: "Get decisions and tasks after a meeting, catch an idea on your wrist, keep a reading note with your interpretation, or collect fragments before writing on desktop.",
        bullets: ["Meeting recap", "Wrist inspiration", "Reading notes", "Writing material"],
      },
    ],
    related: ["features", "watch", "desktop"],
  },
  pricing: {
    group: "Membership & pricing",
    title: "One membership across every device",
    lead: "Monthly is flexible, yearly supports a long-term habit, and lifetime is for people ready to stay. Final taxes and prices are shown by Waffo checkout.",
    heroImage: "https://ideasnap.xyz/assets/showcase/desktop-light-device.webp",
    heroAlt: "IdeaSnap membership experience",
    primary: { label: "Open secure checkout", href: externalLinks.checkout, external: true },
    secondary: { label: "Review features", href: "/features" },
    highlights: [
      { value: "¥18", label: "Monthly" },
      { value: "¥128", label: "Yearly" },
      { value: "Live price", label: "Lifetime early bird" },
    ],
    sections: [
      {
        id: "monthly",
        eyebrow: "Flexible",
        title: "Monthly · ¥18 / month",
        body: "A practical way to experience voice capture, AI organization, and cross-platform sync. Auto-renewal can be managed through the payment channel.",
        bullets: ["Unlimited voice recording", "AI smart summary", "Automatic task extraction", "Cross-platform sync"],
        actions: [{ label: "Choose monthly", href: externalLinks.checkout, external: true }],
      },
      {
        id: "yearly",
        eyebrow: "Recommended",
        title: "Yearly · ¥128 / year",
        body: "Includes the complete monthly benefits and is better suited to an established long-term note habit.",
        bullets: ["All monthly benefits", "Better annual value", "Priority feature updates", "Membership across platforms"],
        actions: [{ label: "Choose yearly", href: externalLinks.checkout, external: true }],
      },
      {
        id: "lifetime",
        eyebrow: "Early bird",
        title: "Lifetime · live Waffo checkout price",
        body: "Purchase once for long-term access to core capabilities. Early-bird pricing may change; checkout is authoritative.",
        bullets: ["One-time purchase", "Core AI capabilities", "Priority feature updates", "Cross-platform membership"],
        actions: [{ label: "Choose lifetime", href: externalLinks.checkout, external: true }],
      },
    ],
    related: ["features", "download", "terms"],
  },
  download: {
    group: "Resources · Download",
    title: "Keep the same note moving across watch, phone, and desktop",
    lead: "Current version: 1.0.18. Use the official packages below and follow the first-launch guidance when your operating system shows a security prompt.",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-illustration.webp",
    heroAlt: "Platforms supported by IdeaSnap",
    primary: { label: "iOS / Apple Watch", href: externalLinks.appStore, external: true },
    secondary: { label: "Android APK", href: externalLinks.android, external: true },
    highlights: [
      { value: "1.0.18", label: "Current version" },
      { value: "6", label: "Platform families" },
      { value: "One account", label: "Notes and membership sync" },
    ],
    sections: [
      {
        id: "mobile-packages",
        eyebrow: "Mobile",
        title: "iPhone, iPad, Apple Watch, and Android",
        body: "Install iOS, iPadOS, and Apple Watch from the App Store. Android uses the official APK. The Watch app comes with the iOS version.",
        bullets: ["iOS / iPadOS / Watch: App Store", "Android: official APK", "Same account for notes and membership"],
        actions: [
          { label: "Open App Store", href: externalLinks.appStore, external: true },
          { label: "Download Android APK", href: externalLinks.android, external: true },
        ],
      },
      {
        id: "desktop-packages",
        eyebrow: "Desktop",
        title: "Windows, macOS, and Linux",
        body: "Windows has Setup and Portable builds, macOS uses DMG, and Linux offers DEB and AppImage packages.",
        bullets: ["Windows: Setup / Portable", "macOS: DMG", "Linux: DEB / AppImage"],
        actions: [
          { label: "Windows Setup", href: externalLinks.windowsSetup, external: true },
          { label: "macOS DMG", href: externalLinks.macos, external: true },
          { label: "Linux DEB", href: externalLinks.linuxDeb, external: true },
        ],
      },
      {
        id: "install",
        eyebrow: "First launch",
        title: "What to do when the system shows a security warning",
        body: "IdeaSnap is a code-signed app. Distribution differences can trigger first-launch prompts on macOS, Android, Windows, or Linux.",
        bullets: ["macOS: Privacy & Security → Open Anyway", "Android: allow the current source", "Windows: More info → Run anyway", "Linux AppImage: grant execute permission"],
        actions: [{ label: "See common questions", href: "/help" }],
      },
    ],
    related: ["mobile", "desktop", "help"],
  },
  mobile: {
    group: "Product · Mobile",
    title: "Speak and capture with IdeaSnap in your pocket",
    lead: "Available on iPhone, iPad, and Android. Ideal for commutes, meetings, and bedtime — say the thought now and organize it later.",
    heroImage: "https://ideasnap.xyz/assets/showcase/mobile-device-ios.webp",
    heroAlt: "IdeaSnap on iOS",
    primary: { label: "Open App Store", href: externalLinks.appStore, external: true },
    secondary: { label: "Android APK", href: externalLinks.android, external: true },
    highlights: [
      { value: "Hold", label: "Fast recording" },
      { value: "Images", label: "Keep attachments" },
      { value: "Sync", label: "Watch and desktop" },
    ],
    sections: [
      {
        id: "record",
        eyebrow: "Fast input",
        title: "Hold the microphone and finish the thought",
        body: "No document setup or template choice. Open IdeaSnap and record when typing is inconvenient or inspiration may disappear.",
        bullets: ["Fast voice capture", "Images and attachments", "Useful in meetings, commutes, and before sleep"],
        image: "https://ideasnap.xyz/assets/showcase/mobile-device-android.webp",
        imageAlt: "IdeaSnap on Android",
      },
      {
        id: "browse",
        eyebrow: "Browse & retrieve",
        title: "Use cards, tags, and search for everyday notes",
        body: "Browse completed notes as cards, filter by tag, or search by keyword. Move to desktop when a note needs deeper editing.",
        bullets: ["Card browsing", "Tag filters", "Keyword search", "Continue on another device"],
      },
      {
        id: "sync",
        eyebrow: "Continuity",
        title: "Use one set of notes with Apple Watch and desktop",
        body: "Mobile bridges wrist capture and desktop organization. The same IdeaSnap account keeps content and membership connected.",
        actions: [
          { label: "Explore Watch", href: "/watch" },
          { label: "Explore desktop", href: "/desktop" },
        ],
      },
    ],
    related: ["watch", "workflow", "download"],
  },
  watch: {
    group: "Product · Apple Watch",
    title: "Raise your wrist. Inspiration does not wait for your phone.",
    lead: "Apple Watch supports ready-to-record, in-recording controls, and note cards. Keep the thought while walking, exercising, or in an impromptu meeting.",
    heroImage: "https://ideasnap.xyz/assets/showcase/watch-device.webp",
    heroAlt: "IdeaSnap on Apple Watch",
    primary: { label: "Install with iOS", href: externalLinks.appStore, external: true },
    secondary: { label: "Explore mobile", href: "/mobile" },
    highlights: [
      { value: "Raise", label: "Ready to record" },
      { value: "Tap", label: "Pause and finish" },
      { value: "Desktop", label: "Continue organizing" },
    ],
    sections: [
      {
        id: "start",
        eyebrow: "Wrist workflow",
        title: "Raise your wrist and tap to start",
        body: "Begin directly from Watch when reaching for a phone is inconvenient. It works well while walking, exercising, or keeping both hands free.",
        bullets: ["Enter ready-to-record quickly", "Tap to start", "Review note cards"],
        image: "https://ideasnap.xyz/assets/showcase/watch-illustration.webp",
        imageAlt: "IdeaSnap Watch recording interface",
      },
      {
        id: "control",
        eyebrow: "Recording controls",
        title: "Pause or finish on your wrist, then let AI organize",
        body: "Pause and end the recording on Watch. Continue transcription, summaries, task extraction, and editing later on mobile or desktop.",
        bullets: ["Pause and resume", "Save and continue the workflow", "Sync with mobile and desktop"],
      },
      {
        id: "install",
        eyebrow: "Installation",
        title: "The Watch app is included with the iOS version",
        body: "Install IdeaSnap on iPhone, then use your Apple Watch app-install settings to add the Watch app. Notes and membership stay on the same account.",
        actions: [{ label: "Download & install", href: "/download" }],
      },
    ],
    related: ["mobile", "workflow", "download"],
  },
  desktop: {
    group: "Product · Desktop",
    title: "Turn captured ideas into lasting notes on your computer",
    lead: "Meeting reviews, long-form organization, search, and archive — desktop is built for deep work on Windows, macOS, and Linux, with light and dark themes.",
    heroImage: "https://ideasnap.xyz/assets/showcase/windows-illustration.webp",
    heroAlt: "IdeaSnap desktop interface",
    primary: { label: "Go to downloads", href: "/download" },
    secondary: { label: "See the workflow", href: "/workflow" },
    highlights: [
      { value: "Search", label: "Find it again" },
      { value: "Edit", label: "Handle long notes" },
      { value: "Light / Dark", label: "Match your environment" },
    ],
    sections: [
      {
        id: "deep-work",
        eyebrow: "Deep organization",
        title: "Handle meeting recordings and long notes without a small screen",
        body: "Read AI summaries, verify tasks, revise transcription, and add context on a larger display. Ideal for meeting review, writing, and long-term archives.",
        bullets: ["Read AI summaries", "Review and edit action items", "Organize long text and writing material"],
        image: "https://ideasnap.xyz/assets/showcase/desktop-light-device.webp",
        imageAlt: "IdeaSnap light desktop theme",
      },
      {
        id: "find",
        eyebrow: "Search & archive",
        title: "Build a retrievable collection with search, tags, and categories",
        body: "Use keyword search, tag filters, and categories to reorganize fragments captured on mobile and Watch into reusable material.",
        bullets: ["Keyword search", "Tag filters", "Categories and archive", "Same-account sync"],
      },
      {
        id: "themes",
        eyebrow: "Interface",
        title: "Light and dark themes for different working environments",
        body: "Use light mode during the day and dark mode at night. The website now includes the same light/dark choice for a consistent experience.",
        image: "https://ideasnap.xyz/assets/showcase/desktop-dark-device.webp",
        imageAlt: "IdeaSnap dark desktop theme",
      },
      {
        id: "platforms",
        eyebrow: "Platforms",
        title: "Windows, macOS, and Linux",
        body: "Windows includes Setup and Portable builds, macOS uses DMG, and Linux offers DEB and AppImage packages.",
        actions: [{ label: "Choose a desktop package", href: "/download#desktop-packages" }],
      },
    ],
    related: ["workflow", "download", "mobile"],
  },
  integrations: {
    group: "Product · Integrations & AI",
    title: "Organize ideas and connect them to your workflow",
    lead: "IdeaSnap uses AI for transcription, summaries, and task extraction, and supports Notion integration. AI requires explicit consent and can be disabled.",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-illustration.webp",
    heroAlt: "IdeaSnap multi-device workflow",
    primary: { label: "Download IdeaSnap", href: "/download" },
    secondary: { label: "Privacy overview", href: "/privacy" },
    highlights: [
      { value: "Transcribe", label: "Voice to text" },
      { value: "Summarize", label: "Key points and structure" },
      { value: "Notion", label: "Authorized integration" },
    ],
    sections: [
      {
        id: "ai",
        eyebrow: "AI organization",
        title: "AI is called only after you actively use it and consent",
        body: "For transcription, organization, and analysis, IdeaSnap may currently use services such as Doubao, OpenAI GPT, or Tongyi Qianwen. You can disable AI in settings.",
        bullets: ["Explicit consent on first use", "AI can be disabled", "No ad profiling or data sale", "Content is not used to train third-party models"],
        actions: [{ label: "Full privacy overview", href: "/privacy" }],
      },
      {
        id: "notion",
        eyebrow: "Notion integration",
        title: "Use Notion authorization to fit IdeaSnap into your system",
        body: "After Notion authorization, the browser returns to IdeaSnap to continue. Make sure the IdeaSnap client is installed on the device.",
        bullets: ["Official Notion authorization", "Existing /notion/callback/ path preserved", "Return to the client through the original URL scheme", "Manage authorization through the relevant service"],
      },
      {
        id: "account",
        eyebrow: "Account & sync",
        title: "Website-purchased membership syncs to every client",
        body: "Sign in with the same IdeaSnap account across web, mobile, Watch, and desktop. Web payments are handled through Waffo secure checkout.",
        actions: [
          { label: "Membership plans", href: "/pricing" },
          { label: "Terms of service", href: "/terms" },
        ],
      },
    ],
    related: ["features", "privacy", "workflow"],
  },
  help: {
    group: "Resources · Help",
    title: "Getting started and common questions",
    lead: "From your first recording to multi-device sync, installation, membership, and privacy — here are answers you can act on immediately.",
    heroImage: "https://ideasnap.xyz/assets/showcase/mobile-device-ios.webp",
    heroAlt: "IdeaSnap mobile notes",
    primary: { label: "See how it works", href: "/workflow" },
    secondary: { label: "Contact us", href: "/contact" },
    highlights: [
      { value: "1", label: "Install and sign in" },
      { value: "2", label: "Speak the first note" },
      { value: "3", label: "Review AI output" },
    ],
    sections: [
      {
        id: "getting-started",
        eyebrow: "Quick start",
        title: "Begin with these three steps",
        body: "Install and sign in on your main device. Record your first thought on mobile or Watch. After transcription and organization, review the title, summary, and tasks, then continue on desktop when needed.",
        bullets: ["Install and use the same account", "Hold the microphone and speak", "Review AI output and add tags"],
      },
      {
        id: "install-faq",
        eyebrow: "Installation",
        title: "What if the operating system blocks the first launch?",
        body: "On macOS, use Privacy & Security → Open Anyway. On Android, allow the current source. On Windows, choose More info → Run anyway in SmartScreen.",
        actions: [{ label: "Full installation guide", href: "/download#install" }],
      },
      {
        id: "account-faq",
        eyebrow: "Account & membership",
        title: "Will website-purchased membership sync?",
        body: "Yes. Sign in with the same IdeaSnap account on iPhone, iPad, Apple Watch, Android, macOS, Windows, and Linux. Cancellation and refund rules follow the payment channel and terms.",
        actions: [{ label: "Terms of service", href: "/terms" }],
      },
      {
        id: "privacy-faq",
        eyebrow: "AI & privacy",
        title: "Is my content used for model training?",
        body: "No. It is not used to train third-party models, sold, or used for advertising profiles. AI requires explicit consent and can be disabled.",
        actions: [{ label: "Privacy overview", href: "/privacy" }],
      },
    ],
    related: ["workflow", "download", "contact"],
  },
  about: {
    group: "About",
    title: "About IdeaSnap",
    lead: "IdeaSnap is an AI voice notes app that captures fleeting ideas and organizes them into content you can keep acting on.",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-hero.webp",
    heroAlt: "IdeaSnap across all supported devices",
    primary: { label: "Explore features", href: "/features" },
    secondary: { label: "Meet developer Beicheng", href: externalLinks.developer, external: true },
    highlights: [
      { value: "2018", label: "Product began" },
      { value: "2025", label: "App Store Editors’ Choice" },
      { value: "15+", label: "Product languages" },
    ],
    sections: [
      {
        id: "origin",
        eyebrow: "Origin",
        title: "Continuously updated since around 2018",
        body: "IdeaSnap received App Store Editors’ Choice in November 2025, and version 3.5 added AI summaries in January 2026. Solving real capture and organization problems matters more than stacking features.",
        bullets: ["Regular incremental releases", "Strong productivity-category performance", "Shaped by real user feedback"],
      },
      {
        id: "developer",
        eyebrow: "Who maintains it",
        title: "Built for the long term by indie developer Beicheng",
        body: "IdeaSnap is not a one-off experiment. Beicheng continues to develop and maintain it with an emphasis on detail, localization, and reliability.",
        actions: [
          { label: "Read the dev log", href: externalLinks.updates, external: true },
          { label: "About Beicheng", href: externalLinks.developer, external: true },
        ],
      },
      {
        id: "focus",
        eyebrow: "What matters",
        title: "Focused on voice capture and AI organization, not all-in-one complexity",
        body: "Continuous updates, privacy, disciplined scope, and a smooth experience across languages and devices guide IdeaSnap’s long-term direction.",
        bullets: ["Keep the product alive through updates", "Care about detail and 15+ languages", "Privacy-first and minimal data collection", "Stay focused on capture and organization"],
      },
    ],
    related: ["features", "privacy", "contact"],
  },
  contact: {
    group: "About · Contact",
    title: "Share a problem, suggestion, or collaboration idea",
    lead: "For product questions, collaboration ideas, or a simple hello, use any channel below. Every message is read carefully.",
    heroImage: "https://ideasnap.xyz/assets/icons/Appicon.png",
    heroAlt: "IdeaSnap app icon",
    primary: { label: "Send an email", href: "mailto:506343891@qq.com", external: true },
    secondary: { label: "Read common questions", href: "/help" },
    highlights: [
      { value: "Email", label: "506343891@qq.com" },
      { value: "WeChat", label: "shine5211314" },
      { value: "GitHub", label: "northcity" },
    ],
    sections: [
      {
        id: "channels",
        eyebrow: "Channels",
        title: "Choose the most convenient way",
        body: "Email is best for product feedback because it can include device details, version, and screenshots. Social channels are useful for following indie-development updates.",
        actions: [
          { label: "Email", href: "mailto:506343891@qq.com", external: true },
          { label: "X / Twitter", href: "https://x.com/chenxi44779232", external: true },
          { label: "GitHub", href: "https://github.com/northcity", external: true },
          { label: "Xiaohongshu", href: "https://xhslink.com/m/7ELB1JL5RId", external: true },
        ],
      },
      {
        id: "feedback",
        eyebrow: "Bugs & suggestions",
        title: "Include these details when reporting an issue",
        body: "Share the platform, operating system, IdeaSnap version, steps before the issue, and whether it can be reproduced consistently.",
        bullets: ["Device and operating system", "IdeaSnap version", "Reproduction steps", "Screenshots without sensitive content"],
      },
      {
        id: "collaboration",
        eyebrow: "Collaboration",
        title: "Meaningful projects are welcome by email",
        body: "Briefly include the project background, collaboration model, timeline, and the value both sides can create.",
      },
    ],
    related: ["help", "about", "features"],
  },
  privacy: {
    group: "Legal · Privacy",
    title: "AI helps organize, but control stays with you",
    lead: "This is a readable privacy summary. The official privacy policy governs the complete legal and data-processing details.",
    heroImage: "https://ideasnap.xyz/assets/showcase/platform-illustration.webp",
    heroAlt: "IdeaSnap multi-device privacy overview",
    primary: { label: "Official privacy policy", href: externalLinks.privacy, external: true },
    secondary: { label: "AI & integrations", href: "/integrations" },
    highlights: [
      { value: "Consent", label: "Before AI use" },
      { value: "Optional", label: "AI can be disabled" },
      { value: "No sale", label: "No ad profiling" },
    ],
    sections: [
      {
        id: "consent",
        eyebrow: "AI use",
        title: "AI features require explicit consent on first use",
        body: "IdeaSnap calls third-party AI services only when you actively use transcription, organization, or related capabilities. AI can be disabled in settings.",
        bullets: ["Explicit consent", "Can be disabled", "Processed only for the requested function"],
      },
      {
        id: "data",
        eyebrow: "Data principles",
        title: "Personal data is not sold or used for advertising profiles",
        body: "IdeaSnap relies on membership revenue, not the sale of user data. Content is not used to train third-party models.",
        bullets: ["No personal-data sale", "No ad profiling", "No third-party model training"],
      },
      {
        id: "official",
        eyebrow: "Official policy",
        title: "Read the official policy for complete legal details",
        body: "This page explains the essentials but does not replace the official policy covering data categories, purposes, providers, and your rights.",
        actions: [{ label: "Open official privacy policy", href: externalLinks.privacy, external: true }],
      },
    ],
    related: ["integrations", "terms", "contact"],
  },
  terms: {
    group: "Legal · Terms",
    title: "Membership, renewal, cancellation, and usage rules",
    lead: "This is a readable service summary. The official terms and payment-channel policies govern purchases, cancellation, refunds, and accounts.",
    heroImage: "https://ideasnap.xyz/assets/showcase/desktop-light-device.webp",
    heroAlt: "IdeaSnap desktop product",
    primary: { label: "Official terms of service", href: externalLinks.terms, external: true },
    secondary: { label: "Membership plans", href: "/pricing" },
    highlights: [
      { value: "Monthly / Yearly", label: "Auto-renewing plans" },
      { value: "Cancelable", label: "Manage by channel" },
      { value: "One account", label: "Benefits sync" },
    ],
    sections: [
      {
        id: "membership",
        eyebrow: "Membership",
        title: "One IdeaSnap account shares membership benefits",
        body: "After purchasing on the website or a supported app, sign in with the same account to access membership on supported platforms.",
      },
      {
        id: "renewal",
        eyebrow: "Renewal & cancellation",
        title: "Manage auto-renewal through the original payment channel",
        body: "Apple, Google, and website subscriptions are managed in their respective channels. After cancellation, access usually continues through the current billing period, subject to channel rules.",
      },
      {
        id: "refund",
        eyebrow: "Refunds & final price",
        title: "Checkout and official terms are authoritative",
        body: "Prices may change by promotion or channel. Final taxes and amounts are shown at checkout. Refund eligibility and timing follow official terms and payment-channel policies.",
        actions: [{ label: "Read official terms", href: externalLinks.terms, external: true }],
      },
    ],
    related: ["pricing", "privacy", "help"],
  },
};

export const detailPages: Record<Locale, Record<PageKey, DetailCopy>> = {
  zh: zhPages,
  en: enPages,
};

export const pageLabels: Record<Locale, Record<PageKey, string>> = {
  zh: {
    features: "功能总览",
    workflow: "使用方法",
    pricing: "会员定价",
    download: "下载与安装",
    mobile: "手机端",
    watch: "手表端",
    desktop: "桌面端",
    integrations: "联动与 AI",
    help: "帮助与常见问题",
    about: "关于闪念",
    contact: "联系我们",
    privacy: "隐私说明",
    terms: "服务条款",
  },
  en: {
    features: "Feature overview",
    workflow: "How it works",
    pricing: "Membership",
    download: "Download & install",
    mobile: "Mobile",
    watch: "Apple Watch",
    desktop: "Desktop",
    integrations: "Integrations & AI",
    help: "Help & FAQ",
    about: "About IdeaSnap",
    contact: "Contact",
    privacy: "Privacy",
    terms: "Terms",
  },
};
